# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

custom:
  function_name: auto_update_cfn_stack
  account_id: "701759196663"

plugins:
  - serverless-pseudo-parameters

# The `service` block is the name of the service
service: cfn-stack-update

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  timeout: 120
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "events:DeleteRule"
        - "events:DisableRule"
        - "events:EnableRule"
        - "events:PutEvents"
        - "events:PutTargets"
        - "events:RemoveTargets"
        - "events:PutRule"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ec2:DescribeImages"
        - "ec2:DescribeInstances"
        - "ec2:StopInstances"
        - "ec2:StartInstances"
      Resource: "*"
    - Effect: "Allow"
      Action:
        -  "cloudformation:CreateStack"
        -  "cloudformation:ListStacks"
        -  "cloudformation:DescribeStacks"
        -  "cloudformation:DescribeStackEvents"
        -  "cloudformation:DescribeStackResources"
        -  "cloudformation:GetTemplate"
        -  "cloudformation:ValidateTemplate"
        -  "cloudformation:UpdateStack"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:AddPermission"
        - "lambda:RemovePermission"
      Resource: arn:aws:lambda:${self:provider.region}:${self:custom.account_id}:function:${self:service}-${self:provider.stage}-${self:custom.function_name}

package:
  exclude:
    - ./**
  include:
    - auto_update_cfn_stack.py
    - cfnresponse.py

# The `functions` block defines what code to deploy
functions:
  auto_update_cfn_stack:
    handler: auto_update_cfn_stack.lambda_handler
    environment:
      ACCOUNT_ID: ${self:custom.account_id}
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      SERVICE: ${self:service}
      FUNCTION_NAME: ${self:custom.function_name}
