# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

plugins:
  - serverless-pseudo-parameters

# The `service` block is the name of the service
service: cfn-update-scheduler

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  timeout: 120
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "events:DeleteRule"
        - "events:DisableRule"
        - "events:EnableRule"
        - "events:PutEvents"
        - "events:PutTargets"
        - "events:RemoveTargets"
        - "events:PutRule"
      Resource: "arn:aws:events:${self:provider.region}:#{AWS::AccountId}:rule/auto-update-*"
    - Effect: "Allow"
      Action:
        -  "cloudformation:DescribeStacks"
        -  "cloudformation:DescribeStackEvents"
      Resource: "*"
    - Effect: "Allow"
      Action:
        -  "cloudwatch:GetMetricStatistics"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:AddPermission"
        - "lambda:RemovePermission"
        - "lambda:GetFunction"
      Resource:
        - arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:functions.cwe_update_target.name}

package:
   individually: true

# The `functions` block defines what code to deploy
functions:
  cfn_auto_update_broker:
    name: ${self:service}-${self:provider.stage}-cfn_auto_update_broker
    handler: cfn_auto_update_broker.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - cfn_auto_update_broker.py
        - cfnresponse.py
    environment:
      REGION: ${self:provider.region}
      FUNCTION_NAME: ${self:functions.cwe_update_target.name}
  cwe_update_target:
    name: ${self:service}-${self:provider.stage}-cwe_update_target
    handler: cwe_update_target.lambda_handler
    package:
      exclude:
        - ./**
      include:
        - cwe_update_target.py
    environment:
      STACK_UPDATE_ARN: arn:aws:iam::#{AWS::AccountId}:role/StackUpdateRole

resources:
  Resources:
    CFNUpdateSchedulerStackUpdateRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: StackUpdateRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - "lambda.amazonaws.com"
                AWS:
                  - Fn::GetAtt: [ IamRoleLambdaExecution, Arn ]
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: StackUpdatePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action: "*"
                  Resource: "*"
    # Outputs:
    #   TEST:
    #     Description: "The ARN of the cfn stack update role"
    #     Value:
    #       Fn::GetAtt: [ CFNUpdateSchedulerStackUpdateRole, Arn ]
    #     # CFNUpdateLambdaArn:
    #     #   Description: The ARN of the cfn stack update lambda function
    #     #   Value:
    #     #    - Fn::GetAtt: [cwe_update_targetLambdaFunction, Arn ]
